'use client'
import { useState } from 'react'
import { supabase } from '@/lib/supabase'

export default function PasoHistorial({ form, up, medsBiblio, alergiasBiblio, intolBiblio, opsBiblio, patsBiblio, molsBiblio, setMedsBiblio, setAlergiasBiblio, setIntolBiblio, setOpsBiblio, setPatsBiblio, setMolsBiblio }: any) {
  const [buscarMed, setBuscarMed] = useState('')
  const [buscarAlerg, setBuscarAlerg] = useState('')
  const [buscarIntol, setBuscarIntol] = useState('')
  const [buscarOp, setBuscarOp] = useState('')
  const [buscarPat, setBuscarPat] = useState('')
  const [buscarMol, setBuscarMol] = useState('')
  const [opConfigurando, setOpConfigurando] = useState<any>(null)
  const [patConfigurando, setPatConfigurando] = useState<any>(null)
  const [molConfigurando, setMolConfigurando] = useState<any>(null)
  const [modalNuevoMed, setModalNuevoMed] = useState(false)
  const [modalNuevaAlerg, setModalNuevaAlerg] = useState(false)
  const [modalNuevaIntol, setModalNuevaIntol] = useState(false)
  const [modalNuevaOp, setModalNuevaOp] = useState(false)
  const [modalNuevaPat, setModalNuevaPat] = useState(false)
  const [modalNuevaMol, setModalNuevaMol] = useState(false)
  const [nuevoNombre, setNuevoNombre] = useState('')

  return (
    <div>
      <div className="g3" style={{marginBottom:10}}>
        {/* MEDICACIÓN */}
        <div className="card">
          <div className="card-title">💊 Medicación</div>
          {form.medicacion.length>0&&<div style={{display:'flex',flexWrap:'wrap',gap:4,marginBottom:8}}>{form.medicacion.map((m:any,i:number)=><div key={i} style={{display:'flex',alignItems:'center',gap:4,padding:'3px 8px',borderRadius:99,background:'var(--gl)',border:'1px solid var(--gm)'}}><span style={{fontSize:10,color:'var(--n)'}}>{m.nombre}</span>{m.frecuencia&&<span style={{fontSize:9,color:'var(--grl)'}}>· {m.frecuencia}</span>}<button onClick={()=>up('medicacion',form.medicacion.filter((_:any,j:number)=>j!==i))} style={{fontSize:10,color:'var(--red)',background:'none',border:'none',cursor:'pointer'}}>✕</button></div>)}</div>}
          <input className="input" placeholder="🔍 Buscar..." value={buscarMed} onChange={e=>setBuscarMed(e.target.value)} style={{marginBottom:6,fontSize:11}}/>
          {buscarMed&&<div style={{border:'1px solid var(--bd)',borderRadius:6,maxHeight:140,overflowY:'auto',marginBottom:6}}>{medsBiblio.filter((m:any)=>m.nombre.toLowerCase().includes(buscarMed.toLowerCase())).slice(0,8).map((m:any)=><div key={m.id} onClick={()=>{const freq=prompt('Frecuencia:','Diario');up('medicacion',[...form.medicacion,{nombre:m.nombre,frecuencia:freq||''}]);setBuscarMed('')}} style={{padding:'6px 10px',cursor:'pointer',fontSize:10,borderBottom:'1px solid var(--bl)'}} onMouseOver={e=>(e.currentTarget as HTMLElement).style.background='var(--gl)'} onMouseOut={e=>(e.currentTarget as HTMLElement).style.background=''}>{m.nombre}</div>)}{medsBiblio.filter((m:any)=>m.nombre.toLowerCase().includes(buscarMed.toLowerCase())).length===0&&<div style={{padding:'6px 10px',fontSize:10,color:'var(--grl)'}}>Sin resultados · <button className="btn btn-t btn-sm" onClick={()=>{setNuevoNombre(buscarMed);setModalNuevoMed(true)}}>+ Añadir</button></div>}</div>}
        </div>
        {/* ALERGIAS */}
        <div className="card">
          <div className="card-title">🌿 Alergias</div>
          {form.alergias.length>0&&<div style={{display:'flex',flexWrap:'wrap',gap:4,marginBottom:8}}>{form.alergias.map((a:string,i:number)=><div key={i} style={{display:'flex',alignItems:'center',gap:4,padding:'3px 8px',borderRadius:99,background:'var(--redl)',border:'1px solid #F5C8C8'}}><span style={{fontSize:10,color:'var(--red)'}}>{a}</span><button onClick={()=>up('alergias',form.alergias.filter((_:any,j:number)=>j!==i))} style={{fontSize:10,color:'var(--red)',background:'none',border:'none',cursor:'pointer'}}>✕</button></div>)}</div>}
          <input className="input" placeholder="🔍 Buscar..." value={buscarAlerg} onChange={e=>setBuscarAlerg(e.target.value)} style={{marginBottom:6,fontSize:11}}/>
          {buscarAlerg&&<div style={{border:'1px solid var(--bd)',borderRadius:6,maxHeight:140,overflowY:'auto',marginBottom:6}}>{alergiasBiblio.filter((a:any)=>a.nombre.toLowerCase().includes(buscarAlerg.toLowerCase())).slice(0,8).map((a:any)=><div key={a.id} onClick={()=>{if(!form.alergias.includes(a.nombre))up('alergias',[...form.alergias,a.nombre]);setBuscarAlerg('')}} style={{padding:'6px 10px',cursor:'pointer',fontSize:10,borderBottom:'1px solid var(--bl)'}} onMouseOver={e=>(e.currentTarget as HTMLElement).style.background='var(--gl)'} onMouseOut={e=>(e.currentTarget as HTMLElement).style.background=''}>{a.nombre}</div>)}{alergiasBiblio.filter((a:any)=>a.nombre.toLowerCase().includes(buscarAlerg.toLowerCase())).length===0&&<div style={{padding:'6px 10px',fontSize:10,color:'var(--grl)'}}>Sin resultados · <button className="btn btn-t btn-sm" onClick={()=>{setNuevoNombre(buscarAlerg);setModalNuevaAlerg(true)}}>+ Añadir</button></div>}</div>}
        </div>
        {/* INTOLERANCIAS */}
        <div className="card">
          <div className="card-title">⚠️ Intolerancias</div>
          {form.intolerancias.length>0&&<div style={{display:'flex',flexWrap:'wrap',gap:4,marginBottom:8}}>{form.intolerancias.map((a:string,i:number)=><div key={i} style={{display:'flex',alignItems:'center',gap:4,padding:'3px 8px',borderRadius:99,background:'var(--ambl)',border:'1px solid var(--amb)'}}><span style={{fontSize:10,color:'#7A5800'}}>{a}</span><button onClick={()=>up('intolerancias',form.intolerancias.filter((_:any,j:number)=>j!==i))} style={{fontSize:10,color:'#7A5800',background:'none',border:'none',cursor:'pointer'}}>✕</button></div>)}</div>}
          <input className="input" placeholder="🔍 Buscar..." value={buscarIntol} onChange={e=>setBuscarIntol(e.target.value)} style={{marginBottom:6,fontSize:11}}/>
          {buscarIntol&&<div style={{border:'1px solid var(--bd)',borderRadius:6,maxHeight:120,overflowY:'auto',marginBottom:6}}>{intolBiblio.filter((a:any)=>a.nombre.toLowerCase().includes(buscarIntol.toLowerCase())).slice(0,8).map((a:any)=><div key={a.id} onClick={()=>{if(!form.intolerancias.includes(a.nombre))up('intolerancias',[...form.intolerancias,a.nombre]);setBuscarIntol('')}} style={{padding:'6px 10px',cursor:'pointer',fontSize:10,borderBottom:'1px solid var(--bl)'}} onMouseOver={e=>(e.currentTarget as HTMLElement).style.background='var(--gl)'} onMouseOut={e=>(e.currentTarget as HTMLElement).style.background=''}>{a.nombre}</div>)}{intolBiblio.filter((a:any)=>a.nombre.toLowerCase().includes(buscarIntol.toLowerCase())).length===0&&<div style={{padding:'6px 10px',fontSize:10,color:'var(--grl)'}}>Sin resultados · <button className="btn btn-t btn-sm" onClick={()=>{setNuevoNombre(buscarIntol);setModalNuevaIntol(true)}}>+ Añadir</button></div>}</div>}
        </div>
      </div>
      <div className="g2" style={{marginBottom:10}}>
        {/* OPERACIONES */}
        <div className="card">
          <div className="card-title">🔪 Operaciones</div>
          {form.operaciones.length>0&&<div style={{marginBottom:8}}>{form.operaciones.map((op:any,i:number)=><div key={i} style={{display:'flex',alignItems:'center',gap:6,padding:'5px 8px',borderRadius:6,background:'var(--bl)',border:'1px solid var(--bd)',marginBottom:4}}><div style={{flex:1}}><div style={{fontSize:10,fontWeight:400,color:'var(--n)'}}>{op.nombre}</div><div style={{fontSize:8,color:'var(--grl)'}}>{op.lado&&op.lado!=='no_aplica'?op.lado+' · ':''}{op.anio&&op.anio+' · '}{op.tiene_informe&&'📄'}</div></div><button onClick={()=>up('operaciones',form.operaciones.filter((_:any,j:number)=>j!==i))} style={{fontSize:10,color:'var(--red)',background:'none',border:'none',cursor:'pointer'}}>✕</button></div>)}</div>}
          <input className="input" placeholder="🔍 Buscar..." value={buscarOp} onChange={e=>setBuscarOp(e.target.value)} style={{marginBottom:6,fontSize:11}}/>
          {buscarOp&&<div style={{border:'1px solid var(--bd)',borderRadius:6,maxHeight:160,overflowY:'auto',marginBottom:6}}>{opsBiblio.filter((op:any)=>op.nombre.toLowerCase().includes(buscarOp.toLowerCase())||op.zona.toLowerCase().includes(buscarOp.toLowerCase())).slice(0,8).map((op:any)=><div key={op.id} onClick={()=>{setOpConfigurando({...op,anio:'',lado:'no_aplica',tiene_informe:false,observaciones:''});setBuscarOp('')}} style={{padding:'6px 10px',cursor:'pointer',fontSize:10,borderBottom:'1px solid var(--bl)'}} onMouseOver={e=>(e.currentTarget as HTMLElement).style.background='var(--gl)'} onMouseOut={e=>(e.currentTarget as HTMLElement).style.background=''}><div>{op.nombre}</div><div style={{fontSize:8,color:'var(--grl)'}}>{op.zona}</div></div>)}{opsBiblio.filter((op:any)=>op.nombre.toLowerCase().includes(buscarOp.toLowerCase())).length===0&&<div style={{padding:'6px 10px',fontSize:10,color:'var(--grl)'}}>Sin resultados · <button className="btn btn-t btn-sm" onClick={()=>{setNuevoNombre(buscarOp);setModalNuevaOp(true)}}>+ Añadir</button></div>}</div>}
        </div>
        {/* PATOLOGÍAS */}
        <div className="card">
          <div className="card-title">🏥 Patologías</div>
          {form.patologias.length>0&&<div style={{marginBottom:8}}>{form.patologias.map((p:any,i:number)=><div key={i} style={{display:'flex',alignItems:'center',gap:6,padding:'5px 8px',borderRadius:6,background:p.estado==='activa'?'var(--redl)':p.estado==='cronica'?'var(--ambl)':'var(--gl)',border:`1px solid ${p.estado==='activa'?'#F5C8C8':p.estado==='cronica'?'var(--amb)':'var(--gm)'}`,marginBottom:4}}><div style={{flex:1}}><div style={{fontSize:10,fontWeight:400,color:'var(--n)'}}>{p.nombre}</div><div style={{fontSize:8,color:'var(--grl)'}}>{p.lado} · {p.estado}{p.tiene_informe&&' · 📄'}</div></div><button onClick={()=>up('patologias',form.patologias.filter((_:any,j:number)=>j!==i))} style={{fontSize:10,color:'var(--red)',background:'none',border:'none',cursor:'pointer'}}>✕</button></div>)}</div>}
          <input className="input" placeholder="🔍 Buscar..." value={buscarPat} onChange={e=>setBuscarPat(e.target.value)} style={{marginBottom:6,fontSize:11}}/>
          {buscarPat&&<div style={{border:'1px solid var(--bd)',borderRadius:6,maxHeight:160,overflowY:'auto',marginBottom:6}}>{patsBiblio.filter((p:any)=>p.nombre.toLowerCase().includes(buscarPat.toLowerCase())||p.zona.toLowerCase().includes(buscarPat.toLowerCase())).slice(0,8).map((p:any)=><div key={p.id} onClick={()=>{setPatConfigurando({...p,lado:'bilateral',estado:'activa',tiene_informe:false,observaciones:''});setBuscarPat('')}} style={{padding:'6px 10px',cursor:'pointer',fontSize:10,borderBottom:'1px solid var(--bl)'}} onMouseOver={e=>(e.currentTarget as HTMLElement).style.background='var(--gl)'} onMouseOut={e=>(e.currentTarget as HTMLElement).style.background=''}><div>{p.nombre}</div><div style={{fontSize:8,color:'var(--grl)'}}>{p.zona} · {p.sistema}</div></div>)}{patsBiblio.filter((p:any)=>p.nombre.toLowerCase().includes(buscarPat.toLowerCase())).length===0&&<div style={{padding:'6px 10px',fontSize:10,color:'var(--grl)'}}>Sin resultados · <button className="btn btn-t btn-sm" onClick={()=>{setNuevoNombre(buscarPat);setModalNuevaPat(true)}}>+ Añadir</button></div>}</div>}
        </div>
      </div>
      {/* MOLESTIAS */}
      <div className="card">
        <div className="card-title">🤕 Molestias</div>
        {form.molestias.length>0&&<div style={{display:'flex',flexWrap:'wrap',gap:5,marginBottom:8}}>{form.molestias.map((m:any,i:number)=>{const color=m.eva>=7?'var(--red)':m.eva>=4?'#7A5800':'var(--gd)';const bg=m.eva>=7?'var(--redl)':m.eva>=4?'var(--ambl)':'var(--gl)';const border=m.eva>=7?'#F5C8C8':m.eva>=4?'var(--amb)':'var(--gm)';return <div key={i} style={{display:'flex',alignItems:'center',gap:5,padding:'4px 10px',borderRadius:99,background:bg,border:`1px solid ${border}`}}><span style={{fontSize:10,color,fontWeight:400}}>{m.zona}</span><span style={{fontSize:8,color}}>EVA {m.eva}</span>{m.lado&&m.lado!=='bilateral'&&<span style={{fontSize:8,color}}>· {m.lado}</span>}<button onClick={()=>up('molestias',form.molestias.filter((_:any,j:number)=>j!==i))} style={{fontSize:9,color,background:'none',border:'none',cursor:'pointer'}}>✕</button></div>})}</div>}
        <input className="input" placeholder="🔍 ej. Dolor lumbar, rodilla..." value={buscarMol} onChange={e=>setBuscarMol(e.target.value)} style={{marginBottom:6,fontSize:11}}/>
        {buscarMol&&<div style={{border:'1px solid var(--bd)',borderRadius:6,maxHeight:180,overflowY:'auto'}}>{molsBiblio.filter((m:any)=>m.nombre.toLowerCase().includes(buscarMol.toLowerCase())||m.zona.toLowerCase().includes(buscarMol.toLowerCase())).slice(0,10).map((m:any)=><div key={m.id} onClick={()=>{setMolConfigurando({nombre:m.nombre,zona:m.zona,tipo:'molestia',eva:5,lado:'bilateral',cuando:'Al moverse',observaciones:''});setBuscarMol('')}} style={{padding:'6px 10px',cursor:'pointer',fontSize:10,borderBottom:'1px solid var(--bl)'}} onMouseOver={e=>(e.currentTarget as HTMLElement).style.background='var(--gl)'} onMouseOut={e=>(e.currentTarget as HTMLElement).style.background=''}><div>{m.nombre}</div><div style={{fontSize:8,color:'var(--grl)'}}>{m.zona}</div></div>)}{molsBiblio.filter((m:any)=>m.nombre.toLowerCase().includes(buscarMol.toLowerCase())).length===0&&<div style={{padding:'6px 10px',fontSize:10,color:'var(--grl)'}}>Sin resultados · <button className="btn btn-t btn-sm" onClick={()=>{setNuevoNombre(buscarMol);setModalNuevaMol(true)}}>+ Añadir</button></div>}</div>}
      </div>

      {/* MODALES CONFIGURAR */}
      {patConfigurando&&<div className="modal-bg" onClick={e=>{if(e.target===e.currentTarget)setPatConfigurando(null)}}><div className="modal"><div className="modal-title">{patConfigurando.nombre}<button className="modal-close" onClick={()=>setPatConfigurando(null)}>✕</button></div>{patConfigurando.precauciones&&<div style={{padding:'6px 9px',background:'var(--ambl)',borderRadius:5,border:'1px solid var(--amb)',fontSize:9,color:'#7A5800',marginBottom:10}}>⚠️ {patConfigurando.precauciones}</div>}<div className="g2"><div className="field"><label>Lado</label><select className="input" value={patConfigurando.lado} onChange={e=>setPatConfigurando((p:any)=>({...p,lado:e.target.value}))}><option value="bilateral">Bilateral</option><option value="izquierdo">Izquierdo</option><option value="derecho">Derecho</option><option value="no_aplica">No aplica</option></select></div><div className="field"><label>Estado</label><select className="input" value={patConfigurando.estado} onChange={e=>setPatConfigurando((p:any)=>({...p,estado:e.target.value}))}><option value="activa">Activa</option><option value="cronica">Crónica</option><option value="resuelta">Resuelta</option></select></div></div><div className="field"><label>Observaciones</label><textarea className="input" style={{minHeight:60}} value={patConfigurando.observaciones} onChange={e=>setPatConfigurando((p:any)=>({...p,observaciones:e.target.value}))}/></div><div onClick={()=>setPatConfigurando((p:any)=>({...p,tiene_informe:!p.tiene_informe}))} style={{display:'flex',alignItems:'center',gap:8,padding:'7px 10px',borderRadius:6,border:`1px solid ${patConfigurando.tiene_informe?'var(--g)':'var(--bd)'}`,background:patConfigurando.tiene_informe?'var(--gl)':'var(--w)',cursor:'pointer',marginBottom:10}}><div style={{width:16,height:16,borderRadius:3,border:`2px solid ${patConfigurando.tiene_informe?'var(--g)':'var(--bd)'}`,background:patConfigurando.tiene_informe?'var(--g)':'transparent',display:'flex',alignItems:'center',justifyContent:'center',flexShrink:0}}>{patConfigurando.tiene_informe&&<span style={{color:'#fff',fontSize:9,fontWeight:700}}>✓</span>}</div><span style={{fontSize:10,color:'var(--n)'}}>📄 Tiene informe médico</span></div><div style={{display:'flex',gap:8}}><button className="btn btn-d btn-sm" onClick={()=>setPatConfigurando(null)}>Cancelar</button><div style={{flex:1}}/><button className="btn btn-p" onClick={()=>{up('patologias',[...form.patologias,{nombre:patConfigurando.nombre,lado:patConfigurando.lado,estado:patConfigurando.estado,tiene_informe:patConfigurando.tiene_informe,observaciones:patConfigurando.observaciones}]);setPatConfigurando(null)}}>✓ Añadir</button></div></div></div>}
      {opConfigurando&&<div className="modal-bg" onClick={e=>{if(e.target===e.currentTarget)setOpConfigurando(null)}}><div className="modal"><div className="modal-title">{opConfigurando.nombre}<button className="modal-close" onClick={()=>setOpConfigurando(null)}>✕</button></div><div className="g2"><div className="field"><label>Año</label><input className="input" value={opConfigurando.anio} onChange={e=>setOpConfigurando((p:any)=>({...p,anio:e.target.value}))} placeholder="ej. 2020"/></div><div className="field"><label>Lado</label><select className="input" value={opConfigurando.lado} onChange={e=>setOpConfigurando((p:any)=>({...p,lado:e.target.value}))}><option value="no_aplica">No aplica</option><option value="izquierdo">Izquierdo</option><option value="derecho">Derecho</option><option value="bilateral">Bilateral</option></select></div></div><div className="field"><label>Observaciones</label><textarea className="input" style={{minHeight:60}} value={opConfigurando.observaciones} onChange={e=>setOpConfigurando((p:any)=>({...p,observaciones:e.target.value}))}/></div><div onClick={()=>setOpConfigurando((p:any)=>({...p,tiene_informe:!p.tiene_informe}))} style={{display:'flex',alignItems:'center',gap:8,padding:'7px 10px',borderRadius:6,border:`1px solid ${opConfigurando.tiene_informe?'var(--g)':'var(--bd)'}`,background:opConfigurando.tiene_informe?'var(--gl)':'var(--w)',cursor:'pointer',marginBottom:10}}><div style={{width:16,height:16,borderRadius:3,border:`2px solid ${opConfigurando.tiene_informe?'var(--g)':'var(--bd)'}`,background:opConfigurando.tiene_informe?'var(--g)':'transparent',display:'flex',alignItems:'center',justifyContent:'center',flexShrink:0}}>{opConfigurando.tiene_informe&&<span style={{color:'#fff',fontSize:9,fontWeight:700}}>✓</span>}</div><span style={{fontSize:10,color:'var(--n)'}}>📄 Tiene informe</span></div><div style={{display:'flex',gap:8}}><button className="btn btn-d btn-sm" onClick={()=>setOpConfigurando(null)}>Cancelar</button><div style={{flex:1}}/><button className="btn btn-p" onClick={()=>{up('operaciones',[...form.operaciones,{nombre:opConfigurando.nombre,anio:opConfigurando.anio,lado:opConfigurando.lado,tiene_informe:opConfigurando.tiene_informe,observaciones:opConfigurando.observaciones}]);setOpConfigurando(null)}}>✓ Añadir</button></div></div></div>}
      {molConfigurando&&<div className="modal-bg" onClick={e=>{if(e.target===e.currentTarget)setMolConfigurando(null)}}><div className="modal"><div className="modal-title">{molConfigurando.nombre}<button className="modal-close" onClick={()=>setMolConfigurando(null)}>✕</button></div><div className="g2"><div className="field"><label>Tipo</label><select className="input" value={molConfigurando.tipo} onChange={e=>setMolConfigurando((p:any)=>({...p,tipo:e.target.value}))}><option value="molestia">Molestia</option><option value="dolor_agudo">Dolor agudo</option><option value="dolor_cronico">Dolor crónico</option><option value="rigidez">Rigidez</option></select></div><div className="field"><label>Lado</label><select className="input" value={molConfigurando.lado} onChange={e=>setMolConfigurando((p:any)=>({...p,lado:e.target.value}))}><option value="bilateral">Bilateral</option><option value="izquierdo">Izquierdo</option><option value="derecho">Derecho</option></select></div></div><div className="field"><label>EVA ({molConfigurando.eva}/10)</label><input type="range" min={0} max={10} value={molConfigurando.eva} onChange={e=>setMolConfigurando((p:any)=>({...p,eva:parseInt(e.target.value)}))} style={{width:'100%',accentColor:'var(--red)'}}/><div style={{display:'flex',justifyContent:'space-between',fontSize:8,color:'var(--grl)'}}><span>0</span><span style={{fontWeight:500,color:'var(--red)'}}>{molConfigurando.eva}</span><span>10</span></div></div><div className="field"><label>¿Cuándo aparece?</label><div style={{display:'flex',gap:5,flexWrap:'wrap',marginTop:4}}>{['En reposo','Al moverse','Con carga','Al caminar','Siempre','Al despertar'].map(c=><span key={c} onClick={()=>setMolConfigurando((p:any)=>({...p,cuando:c}))} style={{fontSize:10,padding:'3px 9px',borderRadius:99,border:`1px solid ${molConfigurando.cuando===c?'var(--g)':'var(--bd)'}`,background:molConfigurando.cuando===c?'var(--g)':'var(--w)',color:molConfigurando.cuando===c?'#fff':'var(--gr)',cursor:'pointer'}}>{c}</span>)}</div></div><div className="field"><label>Observaciones</label><textarea className="input" style={{minHeight:60}} value={molConfigurando.observaciones} onChange={e=>setMolConfigurando((p:any)=>({...p,observaciones:e.target.value}))} placeholder="Sensación, qué lo provoca..."/></div><div style={{display:'flex',gap:8,marginTop:8}}><button className="btn btn-d btn-sm" onClick={()=>setMolConfigurando(null)}>Cancelar</button><div style={{flex:1}}/><button className="btn btn-p" onClick={()=>{up('molestias',[...form.molestias,{zona:molConfigurando.nombre,tipo:molConfigurando.tipo,eva:molConfigurando.eva,lado:molConfigurando.lado,cuando:molConfigurando.cuando,observaciones:molConfigurando.observaciones}]);setMolConfigurando(null)}}>✓ Añadir</button></div></div></div>}

      {/* MODALES NUEVO */}
      {modalNuevoMed&&<div className="modal-bg" onClick={e=>{if(e.target===e.currentTarget)setModalNuevoMed(false)}}><div className="modal"><div className="modal-title">Añadir medicamento<button className="modal-close" onClick={()=>setModalNuevoMed(false)}>✕</button></div><div className="field"><label>Nombre *</label><input className="input" value={nuevoNombre} onChange={e=>setNuevoNombre(e.target.value)} autoFocus/></div><div style={{display:'flex',gap:8,marginTop:8}}><button className="btn btn-d btn-sm" onClick={()=>setModalNuevoMed(false)}>Cancelar</button><div style={{flex:1}}/><button className="btn btn-p" onClick={async()=>{if(!nuevoNombre)return;await supabase.from('medicamentos_biblioteca').insert({nombre:nuevoNombre,categoria:'Otros',activo:true});setMedsBiblio((p:any)=>[...p,{id:Date.now(),nombre:nuevoNombre,categoria:'Otros'}]);const freq=prompt('Frecuencia:','Diario');up('medicacion',[...form.medicacion,{nombre:nuevoNombre,frecuencia:freq||''}]);setModalNuevoMed(false);setNuevoNombre('')}}>💾 Añadir</button></div></div></div>}
      {modalNuevaAlerg&&<div className="modal-bg" onClick={e=>{if(e.target===e.currentTarget)setModalNuevaAlerg(false)}}><div className="modal"><div className="modal-title">Añadir alergia<button className="modal-close" onClick={()=>setModalNuevaAlerg(false)}>✕</button></div><div className="field"><label>Nombre *</label><input className="input" value={nuevoNombre} onChange={e=>setNuevoNombre(e.target.value)} autoFocus/></div><div style={{display:'flex',gap:8,marginTop:8}}><button className="btn btn-d btn-sm" onClick={()=>setModalNuevaAlerg(false)}>Cancelar</button><div style={{flex:1}}/><button className="btn btn-p" onClick={async()=>{if(!nuevoNombre)return;await supabase.from('alergias_biblioteca').insert({nombre:nuevoNombre,categoria:'Otros',activo:true});setAlergiasBiblio((p:any)=>[...p,{id:Date.now(),nombre:nuevoNombre}]);up('alergias',[...form.alergias,nuevoNombre]);setModalNuevaAlerg(false);setNuevoNombre('')}}>💾 Añadir</button></div></div></div>}
      {modalNuevaIntol&&<div className="modal-bg" onClick={e=>{if(e.target===e.currentTarget)setModalNuevaIntol(false)}}><div className="modal"><div className="modal-title">Añadir intolerancia<button className="modal-close" onClick={()=>setModalNuevaIntol(false)}>✕</button></div><div className="field"><label>Nombre *</label><input className="input" value={nuevoNombre} onChange={e=>setNuevoNombre(e.target.value)} autoFocus/></div><div style={{display:'flex',gap:8,marginTop:8}}><button className="btn btn-d btn-sm" onClick={()=>setModalNuevaIntol(false)}>Cancelar</button><div style={{flex:1}}/><button className="btn btn-p" onClick={async()=>{if(!nuevoNombre)return;await supabase.from('intolerancias_biblioteca').insert({nombre:nuevoNombre,categoria:'Otros',activo:true});setIntolBiblio((p:any)=>[...p,{id:Date.now(),nombre:nuevoNombre}]);up('intolerancias',[...form.intolerancias,nuevoNombre]);setModalNuevaIntol(false);setNuevoNombre('')}}>💾 Añadir</button></div></div></div>}
      {modalNuevaOp&&<div className="modal-bg" onClick={e=>{if(e.target===e.currentTarget)setModalNuevaOp(false)}}><div className="modal"><div className="modal-title">Nueva operación<button className="modal-close" onClick={()=>setModalNuevaOp(false)}>✕</button></div><div className="field"><label>Nombre *</label><input className="input" value={nuevoNombre} onChange={e=>setNuevoNombre(e.target.value)} autoFocus/></div><div style={{display:'flex',gap:8,marginTop:8}}><button className="btn btn-d btn-sm" onClick={()=>setModalNuevaOp(false)}>Cancelar</button><div style={{flex:1}}/><button className="btn btn-p" onClick={async()=>{if(!nuevoNombre)return;const {data:nop}=await supabase.from('operaciones_biblioteca').insert({nombre:nuevoNombre,zona:'Otros',activo:true}).select().single();if(nop)setOpsBiblio((p:any)=>[...p,nop]);setOpConfigurando({nombre:nuevoNombre,anio:'',lado:'no_aplica',tiene_informe:false,observaciones:''});setModalNuevaOp(false);setNuevoNombre('')}}>💾 Añadir</button></div></div></div>}
      {modalNuevaPat&&<div className="modal-bg" onClick={e=>{if(e.target===e.currentTarget)setModalNuevaPat(false)}}><div className="modal"><div className="modal-title">Nueva patología<button className="modal-close" onClick={()=>setModalNuevaPat(false)}>✕</button></div><div className="field"><label>Nombre *</label><input className="input" value={nuevoNombre} onChange={e=>setNuevoNombre(e.target.value)} autoFocus/></div><div style={{display:'flex',gap:8,marginTop:8}}><button className="btn btn-d btn-sm" onClick={()=>setModalNuevaPat(false)}>Cancelar</button><div style={{flex:1}}/><button className="btn btn-p" onClick={async()=>{if(!nuevoNombre)return;const {data:np}=await supabase.from('patologias_biblioteca').insert({nombre:nuevoNombre,zona:'Otros',sistema:'Otros',activo:true}).select().single();if(np)setPatsBiblio((p:any)=>[...p,np]);setPatConfigurando({nombre:nuevoNombre,lado:'bilateral',estado:'activa',tiene_informe:false,observaciones:''});setModalNuevaPat(false);setNuevoNombre('')}}>💾 Añadir</button></div></div></div>}
      {modalNuevaMol&&<div className="modal-bg" onClick={e=>{if(e.target===e.currentTarget)setModalNuevaMol(false)}}><div className="modal"><div className="modal-title">Nueva molestia<button className="modal-close" onClick={()=>setModalNuevaMol(false)}>✕</button></div><div className="field"><label>Nombre *</label><input className="input" value={nuevoNombre} onChange={e=>setNuevoNombre(e.target.value)} autoFocus/></div><div style={{display:'flex',gap:8,marginTop:8}}><button className="btn btn-d btn-sm" onClick={()=>setModalNuevaMol(false)}>Cancelar</button><div style={{flex:1}}/><button className="btn btn-p" onClick={async()=>{if(!nuevoNombre)return;const {data:nm}=await supabase.from('molestias_biblioteca').insert({nombre:nuevoNombre,zona:'Otros',activo:true}).select().single();if(nm)setMolsBiblio((p:any)=>[...p,nm]);setMolConfigurando({nombre:nuevoNombre,zona:'Otros',tipo:'molestia',eva:5,lado:'bilateral',cuando:'Al moverse',observaciones:''});setModalNuevaMol(false);setNuevoNombre('')}}>💾 Añadir</button></div></div></div>}
    </div>
  )
}
